//
// Created by Tony Adriansen on 1/1/2024.
//

#ifndef VOXEL_ENGINE_SRC_WORLD_CHUNK_CHUNKVERTEX_HPP_
#define VOXEL_ENGINE_SRC_WORLD_CHUNK_CHUNKVERTEX_HPP_


#endif //VOXEL_ENGINE_SRC_WORLD_CHUNK_CHUNKVERTEX_HPP_
